// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eSocial.Dal;

#nullable disable

namespace eSocial.Dal.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20230718231311_SeedDB")]
    partial class SeedDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.6.23329.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("eSocial.Domain.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Fullstack Developer",
                            CreatedAt = new DateTime(2023, 7, 19, 0, 13, 11, 357, DateTimeKind.Local).AddTicks(5892),
                            LastUpdate = new DateTime(2023, 7, 19, 0, 13, 11, 357, DateTimeKind.Local).AddTicks(5981)
                        },
                        new
                        {
                            Id = 2,
                            Content = "Blazor Developer",
                            CreatedAt = new DateTime(2023, 7, 19, 0, 13, 11, 357, DateTimeKind.Local).AddTicks(5987),
                            LastUpdate = new DateTime(2023, 7, 19, 0, 13, 11, 357, DateTimeKind.Local).AddTicks(5991)
                        },
                        new
                        {
                            Id = 3,
                            Content = ".Net Developer",
                            CreatedAt = new DateTime(2023, 7, 19, 0, 13, 11, 357, DateTimeKind.Local).AddTicks(5996),
                            LastUpdate = new DateTime(2023, 7, 19, 0, 13, 11, 357, DateTimeKind.Local).AddTicks(6000)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
